// This file is generated by Slice Machine. Update with care!

import WorksCarriedOut from './WorksCarriedOut';

export {
	WorksCarriedOut,
};

export const components = {
	works_carried_out: WorksCarriedOut,
};
