import Head from 'next/head';
import Image from 'next/image';
import { Title } from '../components/Title';
import Arrow from '../assets/arrow.svg';
import styles from '../styles/pages/contact.module.scss';
import { useState } from 'react';

export default function Contact() {
  const [messageError, setMessageError] = useState(false);

  function handleClick() {
    setMessageError(true);
  }

  function handleSubmit(e: any) {
    e.preventDefault();
  }

  return (
    <main className={`container content ${styles.contact}`}>
      <Head>
        <title>Entre em Contato - Construágil</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Title
        title="Entre em Contato"
        description="geralmente respondemos em até 24h"
      />
      <nav>
        <iframe
          className={styles.map}
          src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d888.727768940439!2d-51.17105311187783!3d-27.001362598937888!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94e14f1ff9cde647%3A0x95dedfe8a06cf5bf!2sConstruagil!5e0!3m2!1sen!2sbr!4v1585790353637!5m2!1sen!2sbr"
          aria-hidden="false"
        />
        {!!messageError ? (
          <div className={styles.messageError}>
            <h2>Um erro ocorreu!</h2>
            <p>tente para o email construagil@hotmail.com</p>
          </div>
        ) : (
          <form action="" onSubmit={handleSubmit}>
            <label htmlFor="name">
              Nome Completo <span>*</span>
            </label>
            <input type="text" name="name" id="name" />
            <label htmlFor="email">
              E-mail <span>*</span>
            </label>
            <input type="email" name="email" id="email" />
            <label htmlFor="message">
              Mensagem <span>*</span>
            </label>
            <textarea name="message" id="message"></textarea>
            <button type="submit" onClick={handleClick}>
              Enviar
              <Arrow />
            </button>
          </form>
        )}
      </nav>
      <ul>
        <li>
          <Image
            src="/assets/clock.svg"
            width="24"
            height="24"
            alt="Image contact"
          />
          <p>
            De Segunda à Sexta, <br />
            07:30 às 11:30 - 13:00 às 17:30
          </p>
        </li>
        <li>
          <Image
            src="/assets/mail.svg"
            width="24"
            height="24"
            alt="Image contact"
          />
          <p>
            (49) 3566-7982 / 99966-8050 <br />
            construagil@hotmail.com
          </p>
        </li>
        <li>
          <Image
            src="/assets/location.svg"
            width="24"
            height="24"
            alt="Image contact"
          />
          <p>
            Rua Caçador nº1500, <br />
            Panazzolo - Videira-SC
          </p>
        </li>
      </ul>
    </main>
  );
}
