import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import styles from '../styles/pages/home.module.scss';
import Arrow from '../../public/assets/arrow.svg';

import Carousel from 'react-multi-carousel';
import 'react-multi-carousel/lib/styles.css';

export default function Home() {
  const responsive = {
    desktop: {
      breakpoint: { max: 3000, min: 1024 },
      items: 3,
      slidesToSlide: 3, // optional, default to 1.
    },
    tablet: {
      breakpoint: { max: 1024, min: 464 },
      items: 2,
      slidesToSlide: 2, // optional, default to 1.
    },
    mobile: {
      breakpoint: { max: 464, min: 0 },
      items: 1,
      slidesToSlide: 1, // optional, default to 1.
    },
  };
  return (
    <main>
      <Head>
        <title>
          Construágil - Construindo seus sonhos.
          {/* · */}
        </title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <section className={`container ${styles.banner}`}>
        <div>
          <h1>Entre em contato, solicite um orçamento ou visite-nos</h1>
          <Link href="/contato">
            <a>
              Entre em Contato
              <Arrow />
            </a>
          </Link>
        </div>
        <Image
          src="/shared/image-banner.svg"
          alt="Image banner"
          width={550}
          height={365}
        />
      </section>
      <section className={`container ${styles.clients}`}>
        <h2>Conheça nossos clientes</h2>
        <ul>
          <li>
            <span className={styles.overlay}></span>
            <Image
              src="/shared/services/image-1.jpg"
              alt="image service"
              layout="fill"
              objectFit="cover"
            />
          </li>
          <li>
            <span className={styles.overlay}></span>
            <Image
              src="/shared/services/image-2.jpg"
              alt="image service"
              layout="fill"
              objectFit="cover"
            />
          </li>
          <li>
            <span className={styles.overlay}></span>
            <Image
              src="/shared/services/image-3.jpg"
              alt="image service"
              layout="fill"
              objectFit="cover"
            />
          </li>
          <li>
            <span className={styles.overlay}></span>
            <Image
              src="/shared/services/image-4.jpg"
              alt="image service"
              layout="fill"
              objectFit="cover"
            />
          </li>
        </ul>
        <Link href="/servicos">
          <a>
            Ver mais
            <Arrow />
          </a>
        </Link>
      </section>
      <section className={styles.services}>
        <ul className={`container`}>
          <li>
            <div>
              <Image
                src="/icons/truck.svg"
                alt="Truck"
                width={32}
                height={32}
              />
            </div>
            <span>Caçamba, Retroescavadeira e Mini Escavadeira</span>
          </li>
          <li>
            <div>
              <Image
                src="/icons/floor.svg"
                alt="Floor"
                width={32}
                height={32}
              />
            </div>
            <span>Pisos Industriais</span>
          </li>
          <li>
            <div>
              <Image
                src="/icons/buildings.svg"
                alt="Building"
                width={32}
                height={32}
              />
            </div>
            <span>Construção de Casas e Barracões</span>
          </li>
        </ul>
      </section>
      {/* <section className={styles.slide}>
        <div>
          <Carousel
            swipeable={false}
            draggable={false}
            showDots={false}
            responsive={responsive}
            ssr={true} // means to render carousel on server-side.
            infinite={true}
            arrows={true}
            autoPlaySpeed={1000}
            keyBoardControl={true}
            customTransition="all .5"
            transitionDuration={500}
            removeArrowOnDeviceType={['tablet', 'mobile']}
          >
            <div>Item 1</div>
            <div>Item 2</div>
            <div>Item 3</div>
            <div>Item 4</div>
          </Carousel>
        </div>
      </section> */}
    </main>
  );
}
