import Head from 'next/head';
import { Title } from '../components/Title';

export default function Services() {
  return (
    <main className={`container content`}>
      <Head>
        <title>Serviços - Construágil</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Title title="Serviços" description="confira nossos serviços" />
      <section>
        <div className="container">
          <h2>Conheça nossos serviços</h2>
        </div>
      </section>
    </main>
  );
}
