import Head from 'next/head';
import { Title } from '../components/Title';
import styles from '../styles/pages/service.module.scss';
import { useState } from 'react';
import { Clients } from '../components/Clients';

export default function Services() {
  const [vehicleServices, setVehicleServices] = useState(true);
  const [industrialFloors, setIndustrialFloors] = useState(false);
  const [construction, setConstruction] = useState(false);

  function openVehicleService() {
    setVehicleServices(true);
    setConstruction(false);
    setIndustrialFloors(false);
  }

  function openIndustrialFloors() {
    setVehicleServices(false);
    setConstruction(false);
    setIndustrialFloors(true);
  }

  function openConstruction() {
    setVehicleServices(false);
    setConstruction(true);
    setIndustrialFloors(false);
  }

  return (
    <main className={` content ${styles.services}`}>
      <Head>
        <title>Serviços - Construágil</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Title title="Serviços" description="confira nossos serviços" />
      <section className={`${styles.sectionServices}`}>
        <div className="container">
          <h2>Conheça nossos serviços</h2>
          <ul>
            <li>
              <button
                onClick={openVehicleService}
                className={`${vehicleServices && styles.active}`}
              >
                Serviços - máquinas e equipamentos
              </button>
              {vehicleServices && (
                <p>
                  Serviços de retroescavadeira, mini escavadeira e caçamba,
                  rompedor de concreto manual e de rompedor acoplado a mini
                  escavadeira, e retirada de entulho.
                </p>
              )}
            </li>
            <li>
              <button
                onClick={openIndustrialFloors}
                className={`${industrialFloors && styles.active}`}
              >
                Pisos industriais
              </button>
              {industrialFloors && (
                <p>
                  Aplicação de pisos argamassados e autonivelantes, recuperação
                  de pisos danificados, pisos epóxi e polimento de pisos.
                </p>
              )}
            </li>
            <li>
              <button
                onClick={openConstruction}
                className={`${construction && styles.active}`}
              >
                Construção civil
              </button>
              {construction && (
                <p>
                  Construção de casas, prédios e barracões, manutenção e
                  reformas em geral, e pavimentação de calçamento.
                </p>
              )}
            </li>
          </ul>
        </div>
      </section>
      <section className="container">
        <Clients />
      </section>
    </main>
  );
}
